// This file was AUTOMATICALLY GENERATED by dbg-import (smuggol) for github.com/robertkrimen/dbg

package parser

import (
	Dbg "github.com/sqreen/go-agent/internal/sqlib/sqjs/dbg"
)

var dbg, dbgf = Dbg.New()
